name: Publish OCA Ast to crates.io

on:
  push:
    tags:
      - "oca-ast-v*"
env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: oca-ast

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Publish to crates.io
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features
